version: 2

sources:
  - name: sample_data
    description: 'simple information store for each entity'
    database: snowflake_sample_data
    schema: TPCH_SF001
    tables:
      - name: customer
      - name: region
      - name: nation
      - name: supplier


  - name: sample_data_v2
    description: 'simple information store for each entity version 2'
    database: snowflake_sample_data
    schema: TPCDS_SF10TCL
    tables:
      - name: store_sales
        description: 'information about stores sales'
      - name: web_sales
        description: 'information about web sales'